
version: 2

# SOURCES DEFINITIONS
sources:
  - name: recruiting
    schema: recruiting
    tables: 
      - name: stg_users
      - name: stg_exp_user_project_mappings
      - name: stg_exp_locales
      - name: stg_exp_projects
  - name: map
    schema: dim 
    tables:
      - name: dim_country

# TESTS DEFINITIONS
models:
  - name: active_vendors_hly
    columns:
      - name: project_id
        tests:
          - not_null
