name: 'shared_project'
version: '1.0.0'
config-version: 2

profile: 'shared_project'

test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shared_project:
