version: 2

# SOURCES DEFINITIONS
sources:
  - name: r_shasta
    schema: r_shasta
    tables:
      - name: ip_check
  - name: qrp
    schema: qrp
    tables:
      - name: users

# TESTS DEFINITIONS
models:
  - name: ip_check
    columns:
      - name: ip
        tests:
          - not_null
      - name: created
        tests:
          - not_null
